export default {
  products: [
    {
      _id: '1',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/f8a8c973-523a-4218-995d-d372f7c29f22/lakers-mens-nba-t-shirt-Rwp0Wn.jpg',
      price: 60,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: '2',
      name: 'Fit Shirt',
      category: 'Shirts',
      image: 'https://static.nike.com/a/videos/t_PDP_1280_v1/f_auto,q_auto:eco,so_0.1/0e744966-f8f8-4aae-97a5-2761f14798a6/dri-fit-mens-training-t-shirt-nhgSHx.jpg',
      price: 50,
      brand: ' Nike',
      rating: 4.2,
      numReviews: 5,
    },
    {
      _id: '3',
      name: 'Best Pants',
      category: 'Pants',
      image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/xnsfrzt7wizaxgxrtdkq/therma-mens-tapered-training-pants-LxQQ75.jpg',
      price: 70,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
    },
    {
      _id: '4',
      name: 'Best Pants',
      category: 'Pants',
      image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/4f3570b5-c045-4e89-ac4e-be4fb3a70dcb/sportswear-essential-womens-fleece-pants-54QNq7.jpg',
      price: 70,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
    },
  ],
};